apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: jenkins
  labels:  
    app: jenkins
  namespace: jenkins
spec:
  replicas: 2
  template:
    metadata:
      name: jenkins
      labels:
        apps: jenkins
    spec:
      containers:
      - name: jenkins
        image: timperry1994/jenkins:0.1
        ports:
        - containerPort: 8080
        livenessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 120
          timeoutSeconds: 10      
