apiVersion:v1
kind: Service
metadata:
  name: jenkins-serv
  namespace: jenkins
spec:
  type: NodePort
  selector: 
    app: master
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
    name: serv
